### PR TITLE
IR-224: Bump openshift/api

### PR DESCRIPTION
**Pull request by flavianmissi**
also bumps a few related packages as well to fix compilation errors
in some of the vendored packages.

The only changes needed to support the new versions were adding
context to some calls. Used `context.TODO()` for that.

Closes https://issues.redhat.com/browse/IR-224

### CODE REVIEW

**Comment by flavianmissi** [comment]
running `make test` myself against a 4.9 cluster gives me no failures. 
@dmage could this mean the test failures are prow related?

**Comment by dmage** [comment]
@flavianmissi red are `e2e-*-operator`, i.e. e2e tests, you can run them via `make test-e2e`.

**Comment by dmage** [comment]
Lots of failures should be addressed by https://github.com/openshift/cluster-image-registry-operator/pull/726

**Comment by flavianmissi** [comment]
> you can run them via `make test-e2e`.

@dmage yes! and `make test` will [run both](https://github.com/openshift/cluster-image-registry-operator/blob/master/Makefile#L28) `test-unit` and `test-e2e`

**Comment by dmage** [comment]
/lgtm

No customer facing changes.
/label px-approved
/label docs-approved

**Comment by dmage** [comment]
/assign @xiuwang @wewang58 
for QE approval

**Comment by xiuwang** [comment]
Doing regression test, will add result back

**Comment by xiuwang** [comment]
Regression passed
/lgtm
/label qe-approved
